name: Damg
on:
  push:
    branches:
      - main
      - test
jobs: 
  build:
    name: Code-integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Directory
        run: ls -al

      - name: Create env
        run: |
          cd Application && \
          printf "%s" "${{ secrets.ENTIRE_ENV }}" > .env

      - name: Docker Install
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: Free Disk Space
        run: docker system prune -af

      - name: Docker Compose Build
        run: |
          cd Application && \
          docker version && \
          docker compose up --build --no-cache

      - name: Cleanup
        run: docker compose down
