name: Damg

on:
  push:
    branches:
      - main
     
jobs: 
  build:
    name: Code-integration-deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Directory
        run: ls -al

      - name: Create .env File
        run: |
          cd Application
          printf "%s" "${{ secrets.ENTIRE_ENV }}" > .env

      - name: Docker Install
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: Docker Compose Build
        run: |
          cd Application
          set -x

          docker version

          docker compose build