name: Damg
on:
  push:
    branches:
      - main
      - test
jobs: # 'jobs' should be plural
  build:
    name: Code-integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
