name: Damg
on:
  push:
    branches:
      - main
      - test
jobs: 
  build:
    name: Code-integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create env
        run: |
          cd Application \
          echo "${{ secrets.ENTIRE_ENV }}" > .env


